apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tomcat-server
  labels: 
    app: tomcat-server
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    annotations:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
- kind: "BuildConfig"
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    runPolicy: "Serial" 
    triggers: 
      - type: "GitHub"
        github:
          secret: ${SECRET}
      - type: "Generic"
        generic:
          secret: ${SECRET}
      - type: "ConfigChange"
      - imageChangeParams:
          automatic: true 
    source: 
      git:
        uri: ${APP_GIT_URL}
      contextDir: java
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile    
    output: 
      pullSecret:
        name: credquay
      to:
        kind: "ImageStreamTag"
        name: ${APP_NAME}:latest
- kind: "DeploymentConfig"
  apiVersion: apps.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    template: 
      metadata:
        labels:
          name: ${APP_NAME}
          app: ${APP_NAME}
      spec:
        containers:
          - env:
            - name: TOMCAT_USERNAME
            - name: TOMCAT_PASSWORD
            name: ${APP_NAME}
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always
    replicas: 1 
    triggers:
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: "ImageStreamTag"
            name: ${APP_NAME}:latest
    strategy: 
      type: "Rolling"
    paused: false 
    revisionHistoryLimit: 2 
    minReadySeconds: 0 
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
    annotations:
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    port:
      targetPort: 8080-tcp
  wildcardPolicy: None
parameters:
- name: APP_NAME
  displayName: Application Name
  description: Nama aplikasi dan namespace
  value: tomcat-server
  required: true
- name: APP_GIT_URL
  displayName: Application Source Git URL
  description: The Git URL of the application source code
  required: true
  value: https://vohanks354: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@github.com/vohanks354/openshift_project.git
- name: SECRET
  displayName: Webhook Secret
  description: Secret for webhooks
  value: tomcat